### ISSUE TITLE
Consult

### ISSUE THREAD

**Issue by July1991** [IraKorshunova/CNN#1]
What essence difference between CNN algorithm for processing EEG data and CNN algorithm for image data processing

**Comment by IraKorshunova** [comment]
Hi! The main difference is that convolution is done only along the time axis.  This CNN folder contains my very old code. I think you'd better take a look at [kaggle-seizure-prediction](https://github.com/IraKorshunova/kaggle-seizure-prediction)

**Comment by July1991** [comment]
oh,I know ,let me think for a while,thank you for your answer.
